apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configuration
data: 
  prometheus.yml: |- 
    global:
      scrape_interval: 30s
      scrape_timeout: 30s
      evaluation_interval: 20s
    alerting:
      alertmanagers:
      - static_configs:
        - targets: []
        scheme: http
        timeout: 10s
    scrape_configs:
    - job_name: prometheus
      scrape_interval: 25s
      scrape_timeout: 20s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - localhost:9090
        