apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configuration
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: Demo Alert
        expr: sum(go_gc_duration_seconds) > 10
        for: 10m
        labels:
          severity: High
        annotations:
          summary: Golang garbage collector is taking to much time to be executed
  prometheus.yml: |-
    global:
      scrape_interval: 30s
      scrape_timeout: 30s
      evaluation_interval: 20s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - static_configs:
        - targets: []
        scheme: http
        timeout: 10s
    scrape_configs:
    - job_name: prometheus
      scrape_interval: 25s
      scrape_timeout: 20s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - localhost:9090
        
          