apiVersion: v1
kind: Service
metadata:
  name: monitoring-prometheus
  labels:
    app: prometheus-service
spec:
  ports:
  - port: 9090
    targetPort: 9090
  type: NodePort
  selector:
    app: prometheus-app